controlPlaneEventsQueue: ~
dataPlaneEventsQueue: ~
logLevel: debug

secret:
  # You must set the connection string for the postgres queue
  postgresConnectionString: ~
  # Or you can use an existing secret instead
  useExistingSecret: ~

externalSecrets:
  refreshInterval: "5m"
  parameterStore:
    name: "secret-store-parameter-store"
    kind: ClusterSecretStore
  secretName: ~
  secretRegex: ~

serviceMonitors:
  coredb:
    enabled: true

image:
  repository: quay.io/coredb/conductor
  tag: "latest"
  pullPolicy: IfNotPresent

# We should reconfigure the defaults
# once we have more information about this
# workload in practice.
resources:
  limits:
    cpu: 1000m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  annotations: {}
  # Defaults to match name of deployment,
  # when this is set to empty string.
  name: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
