apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: my-coredb
spec:
  appServices:
    - name: my-app
      image: crccheck/hello-world:latest
      routing:
        - port: 8000
          ingressPath: /
