apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: sample-document
spec:
  image: "quay.io/tembo/standard-cnpg:15.3.0-1-1096aeb"
  stop: false
  stack:
    name: Document
  appServices:
    - name: fdb-api
      image: ghcr.io/ferretdb/ferretdb
      routing:
        - port: 27017
          ingressPath: /ferretdb/v1
      env:
        - name: FERRETDB_POSTGRESQL_URL
          valueFromPlatform: ReadWriteConnection
      storage:
        volumes:
          - name: ferretdb-data
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Gi
        volumeMounts:
            - name: ferretdb-data
              mountPath: /state
