apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: sample-standard-restore
  namespace: restore
spec:
  image: "quay.io/tembo/standard-cnpg:15.3.0-1-45c2054"
  backup:
    destinationPath: s3://tembo-backup/sample-standard-restore
    retentionPolicy: "30"
    schedule: 17 9 * * *
    endpointURL: http://minio.minio.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: s3creds
        key: MINIO_ACCESS_KEY
      secretAccessKey:
        name: s3creds
        key: MINIO_SECRET_KEY
  restore:
    serverName: sample-standard-backup
    recoveryTargetTime: "2023-09-26T23:30:29Z"
    endpointURL: http://minio.minio.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: s3creds
        key: MINIO_ACCESS_KEY
      secretAccessKey:
        name: s3creds
        key: MINIO_SECRET_KEY
  stop: false
  stack:
    name: Standard
    postgres_config:
      - name: autovacuum_vacuum_cost_limit
        value: "-1"
      - name: autovacuum_vacuum_scale_factor
        value: "0.05"
      - name: autovacuum_vacuum_insert_scale_factor
        value: "0.05"
      - name: autovacuum_analyze_scale_factor
        value: "0.05"
      - name: checkpoint_timeout
        value: "10min"
      - name: track_activity_query_size
        value: "2048"
      - name: wal_compression
        value: 'on'
      - name: track_io_timing
        value: 'on'
      - name: log_min_duration_statement
        value: "1000"
      - name: pg_stat_statements.track
        value: all
      - name: shared_preload_libraries
        value: pg_stat_statements
  trunk_installs:
    - name: pg_stat_statements
      version: 1.10.0
  extensions:
    - name: pg_stat_statements
      locations:
        - database: postgres
          enabled: true
          version: 1.10.0
  runtime_config:
    - name: shared_buffers
      value: "256MB"
    - name: max_connections
      value: "107"
    - name: work_mem
      value: "5MB"
    - name: bgwriter_delay
      value: "200ms"
    - name: effective_cache_size
      value: "716MB"
    - name: maintenance_work_mem
      value: "64MB"
    - name: max_wal_size
      value: "2GB"
