apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: sample-app
spec:
  appServices:
    - name: my-app
      image: crccheck/hello-world:latest
      ports:
        - "8000:8000"
      ingress:
        enabled: true
        routes:
        - containerPort: 8000
          path: /
