{
 "title": "Cloud Tracker",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "min_sessions_to_consider_active",
    "query": "7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Deployments Under Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "ADUM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[24h]))) > bool ($min_sessions_to_consider_active - 1))\n",
     "legendFormat": "24 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[12h]))) > bool ($min_sessions_to_consider_active - 1))",
     "legendFormat": "12 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[4h]))) > bool ($min_sessions_to_consider_active - 1))",
     "legendFormat": "4 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[1h]))) > bool ($min_sessions_to_consider_active - 1))",
     "legendFormat": "1 hour"
    }
   ]
  },
  {
   "title": "Idle (inverse of active)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[24h]))) < bool ($min_sessions_to_consider_active - 1))\n",
     "legendFormat": "24 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[12h]))) < bool ($min_sessions_to_consider_active - 1))",
     "legendFormat": "12 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[4h]))) < bool ($min_sessions_to_consider_active - 1))",
     "legendFormat": "4 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[1h]))) < bool ($min_sessions_to_consider_active - 1))",
     "legendFormat": "1 hour"
    }
   ]
  },
  {
   "title": "Max number of simultaneous sessions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum by (namespace) (max_over_time(pg_stat_activity_count{}[24h])))\n",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "(sum by (namespace) (max_over_time(pg_stat_activity_count{}[12h])))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (namespace) (max_over_time(pg_stat_activity_count{}[4h])))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (namespace) (max_over_time(pg_stat_activity_count{}[1h])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Utilization of databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(sum by (namespace) (max_over_time(pg_stat_activity_count{}[1m])))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "(sum by (namespace) (irate(pg_stat_database_xact_commit{}[1h])))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Simplified uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Uptime (7 days)",
   "type": "stat",
   "description": "Percent of time control plane database is running",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(avg_over_time(avg by (namespace) (kube_pod_container_status_ready{container=\"postgres\"})[7d:30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "description": "Status of control plane DB",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum((sum by (namespace) (pg_up{namespace=~\"org-coredb-inst-control-plane-.*\"})) OR on() vector(0))",
     "legendFormat": "up"
    }
   ]
  }
 ]
}