{
 "title": "Data plane dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   { "name": "event_search", "label": "Event search" }
  ]
 },
 "panels": [
  { "title": "Postgres storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total allocated persistent block storage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(persistentvolumeclaim) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block storage utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum by(persistentvolumeclaim) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\"}) / sum by(persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\"})",
     "legendFormat": "__auto"
    },
    { "expr": "1", "legendFormat": "limit" }
   ]
  },
  {
   "title": "Kubernetes cluster capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Node Utilization %",
     "type": "timeseries",
     "description": "Nodes run consolidation on a schedule, and should pack more densely when the schedule is triggered.",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "avg(((karpenter_nodes_total_pod_requests{resource_type=\"memory\"} or karpenter_nodes_allocatable*0 + karpenter_nodes_total_daemon_requests{resource_type=\"memory\"} or karpenter_nodes_allocatable*0) *100) / karpenter_nodes_allocatable{resource_type=\"memory\"})",
       "legendFormat": "Memory"
      },
      {
       "expr": "avg(((karpenter_nodes_total_pod_requests{resource_type=\"cpu\"} or karpenter_nodes_allocatable*0 + karpenter_nodes_total_daemon_requests{resource_type=\"cpu\"} or karpenter_nodes_allocatable*0) *100) / karpenter_nodes_allocatable{resource_type=\"cpu\"})",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Spot fraction",
     "type": "timeseries",
     "description": "Total memory categorized by spot / on-demand",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (capacity_type) (karpenter_nodes_allocatable{resource_type=\"memory\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total memory",
     "type": "timeseries",
     "description": "How much total memory is in the cluster for workloads. This number is the sum of all nodes the amount of memory per node available for scheduling workloads, so this number is less than the sum of all memory in the cluster.",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (node_name,instance_type) (karpenter_nodes_allocatable{resource_type=\"memory\"})",
       "legendFormat": "{{node_name}}: {{instance_type}}"
      }
     ]
    },
    {
     "title": "Total CPU",
     "type": "timeseries",
     "description": "How much total CPU is in the cluster for workloads. This number is the sum of all nodes the amount of CPU per node available for scheduling workloads, so this number is less than the sum of all CPU in the cluster.",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (node_name,instance_type) (karpenter_nodes_allocatable{resource_type=\"cpu\"})",
       "legendFormat": "{{node_name}}: {{instance_type}}"
      }
     ]
    },
    {
     "title": "Memory by instance type",
     "type": "timeseries",
     "description": "Total memory categorized by instance types",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance_type) (karpenter_nodes_allocatable{resource_type=\"memory\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU by instance type",
     "type": "timeseries",
     "description": "Total CPU categorized by instance types",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance_type) (karpenter_nodes_allocatable{resource_type=\"cpu\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Node replacement troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres or Grafana containers not running",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "(kube_pod_container_status_running{container=~\"postgres|grafana\"} < 1) + 1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Events",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "{namespace=\"monitoring\", app=\"k8s-event-logger\"} |= `$event_search` | json"
      }
     ]
    },
    {
     "title": "Spot interruptions",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "{namespace=\"monitoring\", app=\"k8s-event-logger\"} |= `InstanceSpotInterrupted` | json"
      }
     ]
    },
    {
     "title": "Pods not running or succeeded",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase!~\"Running|Succeeded\"} > 0",
       "legendFormat": "{{phase}} : {{pod}}"
      }
     ]
    },
    {
     "title": "Spot interruptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "count_over_time({namespace=\"monitoring\", app=\"k8s-event-logger\"} |= `InstanceSpotInterrupted` [$__interval])",
       "legendFormat": "interrupts"
      }
     ]
    },
    {
     "title": "Hours running per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "(time() - kube_node_created{node!~\"fargate-.*\"}) / 3600",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "New nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "(((time() - kube_node_created{node!~\"fargate-.*\"}) / 3600) < bool 4) > 0",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}