{
 "title": "Control Plane Queues",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number Messages in Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pgmq_queue_length{job=\"org-coredb-inst-cp-queue-prd-metrics\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Oldest Message Age (minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgmq_oldest_msg_age_sec{job=\"org-coredb-inst-cp-queue-prd-metrics\"} / 60",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Youngest Message Age (minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgmq_newest_msg_age_sec{job=\"org-coredb-inst-cp-queue-prd-metrics\"} / 60",
     "legendFormat": "{{queue_name}}"
    }
   ]
  }
 ]
}