apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: test-coredb
spec:
  extensions: []
  image: quay.io/coredb/coredb-pg-slim:f57e860
  pkglibdirStorage: 1Gi
  port: 5432
  postgresExporterEnabled: true
  postgresExporterImage: quay.io/prometheuscommunity/postgres-exporter:v0.12.1
  replicas: 1
  sharedirStorage: 1Gi
  storage: 1Gi
  uid: 999
