apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: test-coredb
  namespace: default
spec:
  extensions: []
  image: quay.io/coredb/coredb-pg-slim:f57e860
  pkglibdirStorage: 1Gi
  port: 5432
  postgresExporterEnabled: true
  postgresExporterImage: quay.io/prometheuscommunity/postgres-exporter:v0.12.1
  replicas: 1
  sharedirStorage: 1Gi
  storage: 1Gi
  uid: 999
  runtime_config:
    - name: pg_stat_statements.track
      value: 'top'
    - name: archive_timeout 
      value: '10min'
    - name: dynamic_shared_memory_type
      value: 'posix'
    - name: log_destination 
      value: 'csvlog'
    - name: log_directory 
      value: '/controller/log'
    - name: log_filename 
      value: 'postgres'
    - name: log_rotation_age 
      value: '0'
    - name: log_rotation_size
      value: '0'
    - name: log_truncate_on_rotation
      value: 'false'
    - name: logging_collector 
      value: 'on'
    - name: max_parallel_workers 
      value: '32'
    - name: max_replication_slots 
      value: '32'
    - name: max_worker_processes 
      value: '32'
    - name: shared_memory_type 
      value: 'mmap'
    - name: wal_keep_size 
      value: '512MB'
    - name: wal_receiver_timeout 
      value: '5s'
    - name: wal_sender_timeout 
      value: '5s'
    - name: pg_stat_statements.track
      value: 'top'
