apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tembo-pod-init.fullname" . }}
  namespace: {{ template "tembo-pod-init.namespace" . }}
  labels:
{{ include "tembo-pod-init-helm.labels" . | indent 4 }}
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["pods", "replicasets", "jobs", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["postgresql.cnpg.io"]
  resources: ["backups", "clusters", "poolers", "scheduledbackups"]
  verbs: ["get", "list", "watch"]
