{{- if and (not .Values.secret.queueConnectionString) (not .Values.secret.useExistingSecret) -}}
{{ fail "Neither values.queueConnectionString nor values.secret.useExistingSecret are set. One of them must be set to continue with the installation." }}
{{- end }}
{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reconciler.fullname" . }}
type: Opaque
data:
  connection: {{ .Values.secret.queueConnectionString }}
{{- end }}
