{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podMetricsEndpoints:
  - path: {{ .Values.podMonitor.path }}
    port: {{ .Values.podMonitor.port }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "conductor.selectorLabels" . | nindent 6 }}
{{- end }}
