{{- if .Values.serviceMonitors.coredb.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "conductor.fullname" . }}-coredbs
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - path: /metrics
    port: "metrics"
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: postgres-exporter
      component: metrics
{{- end }}
