apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: test-coredb
spec:
  extensions: []
  image: quay.io/tembo/tembo-pg-cnpg:15.3.0-5-48d489e
  pkglibdirStorage: 1Gi
  port: 5432
  postgresExporterEnabled: true
  postgresExporterImage: quay.io/prometheuscommunity/postgres-exporter:v0.12.1
  replicas: 1
  sharedirStorage: 1Gi
  storage: 1Gi
  uid: 999
