name: conductor image build and upload

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Check out the coredb repo to reuse some actions
        uses: actions/checkout@v3
        with:
          repository: coredb-io/coredb
          path: ./coredb
          ref: release/2023.2.15
      - uses: azure/setup-kubectl@v3
      - uses: azure/setup-helm@v3
      - name: Set version strings
        id: versions
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and upload operator image
        uses: ./coredb/.github/actions/build-and-push-to-quay
        with:
          image_name: conductor
          publish_latest: true
          publish_calver: true
          docker_directory: ./conductor
          quay_user: ${{ secrets.QUAY_USER }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
