name: Dataplane webserver test

defaults:
  run:
    shell: bash
    working-directory: ./dataplane-webserver/

on:
  push:
    paths:
    - '.github/workflows/dataplane-webserver-test.yml'
    - 'dataplane-webserver/**'

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "dataplane-webserver-lint"
          workspaces: |
            dataplane-webserver
      - name: Cargo format
        run: cargo +nightly fmt --check
      - name: Clippy
        run: cargo clippy -- -Dwarnings

  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "dataplane-webserver-test"
          workspaces: |
            dataplane-webserver
      - name: Run tests
        run: |
          set -xe
          export PROMETHEUS_URL=https://prometheus-data-1.use1.dev.plat.cdb-svc.com
          cargo test
