name: Lint Helm charts

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'charts/**'

jobs:
  find_directories:
    name: Find changed helm charts
    runs-on: ubuntu-20.04
    outputs:
      directories: ${{ steps.find_directories.outputs.build_matrix }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Check out the coredb repo to reuse some actions
        uses: actions/checkout@v3
        with:
          repository: coredb-io/coredb
          path: ./.coredb
          ref: 84664df742ce9774a3029e08111940f9f1fb345e
      - name: Find directories with Dockerfiles that changed
        id: find_directories
        uses: ./.coredb/.github/actions/find-changed-directories
        with:
          contains_the_file: Chart.yaml
          changed_relative_to_branch: ${{ github.base_ref || 'not-a-branch' }}
          ignore_dirs: ".coredb"

  lint:
    name: Build and push images
    runs-on: ubuntu-latest
    needs:
      - find_directories
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find_directories.outputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Helm init
        uses: azure/setup-helm@v3
        with:
          version: v3.4.0
      - name: Helm lint
        run: helm lint ${{ matrix.path }}
