name: Operator workflow

permissions:
  pull-requests: write
  deployments: write
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: ./coredb-operator/

on:
  pull_request:
    branches:
      - main
    paths:
    - '.github/workflows/operator.yaml'
    - 'coredb-operator/**'
  push:
    branches:
      - main
    paths:
    - '.github/workflows/operator.yaml'
    - 'coredb-operator/**'

jobs:
  functional_test:
    name: Run functional testing
    runs-on:
      - self-hosted
      - dind
      - large-8x8
    strategy:
      # fail-fast means to cancel all jobs if one fails
      fail-fast: false
      matrix:
        # Go here for a list of versions:
        # https://github.com/kubernetes-sigs/kind/releases
        kube_version:
          - '1.25.8'
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          set -xe
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev git
      - uses: extractions/setup-just@v1
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.7.0
        with:
          install_only: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "coredb-operator-functional-test"
          workspaces: |
            coredb-operator
      - name: Check CRD is updated in the charts directory
        run: |
          set -xe
          cargo run --bin crdgen > ../charts/coredb-operator/templates/crd.yaml
          git diff --exit-code ../charts/coredb-operator/templates/crd.yaml
      - name: Setup local test cluster
        run: |
          set -xe
          export KUBE_VERSION=${{ matrix.kube_version }}
          just start-kind
      - name: Run functional / integration tests
        run: |
          set -xe
          export ENABLE_INITIAL_BACKUP=false
          export DATA_PLANE_BASEDOMAIN=localhost
          # Start the operator in the background
          cargo run &
          # Run the tests
          cargo test -- --ignored --nocapture
      - name: Debugging information
        if: always()
        run: |
          set +e
          set -x
          echo "=========="
          kubectl get pods --all-namespaces
          echo "=========="
          kubectl get -o yaml sts
          echo "=========="
          kubectl get -o yaml svc
          echo "=========="
          kubectl get -o yaml pods
          echo "=========="
          kubectl get -o yaml coredb
          echo "=========="
