name: Reconciler image build and upload

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Check out the coredb repo to reuse some actions
        uses: actions/checkout@v3
        with:
          repository: coredb-io/coredb
          path: ./coredb
          ref: release/2023.2.15
      - uses: azure/setup-kubectl@v3
      - uses: azure/setup-helm@v3
      - name: Build and upload operator image
        uses: ./coredb/.github/actions/build-and-push-to-quay
        with:
          image_name: reconciler
          publish_latest: true
          publish_calver: true
          docker_directory: ./reconciler
          quay_user: ${{ secrets.QUAY_USER }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_OLD_ACCOUNT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_OLD_ACCOUNT }}
          aws-region: us-east-1
      - name: Configure Kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name coredb-pgaas
      - name: Update the reconciler
        run: |
          helm upgrade \
            --install \
            --set secret.useExistingSecret='queue-conn' \
            --set dataPlaneEventsQueue=data_plane_events \
            --set controlPlaneEventsQueue=saas_queue \
            --namespace reconciler \
            reconciler \
            charts/reconciler
          kubectl rollout restart --namespace reconciler deployments || true
