name: reconciler-deploy workflow

defaults:
  run:
    shell: bash
    working-directory: ./reconciler/

on:
  workflow_run:
    workflows: [ reconciler-lint workflow ]
    types:
      - completed
    branches:
      - main
      - release**

permissions:
  id-token: write
  contents: read

jobs:
  push_to_registry:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set version strings
        id: versions
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          # If we publish multiple versions on the same day,
          # we overwrite the previous versions.
          echo "CAL_VER=$(date '+%Y.%m.%d')" >> $GITHUB_OUTPUT
      - name: Build image
        run: |
          set -xe
          docker build -t reconciler ./reconciler
          docker tag reconciler reconciler:latest
          docker tag reconciler reconciler:${{ steps.versions.outputs.CAL_VER }}
          docker tag reconciler reconciler:${{ steps.versions.outputs.SHORT_SHA }}
      - name: Push To quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: quay.io/coredb
          image: reconciler
          tags: latest ${{ steps.versions.outputs.CAL_VER }} ${{ steps.versions.outputs.SHORT_SHA }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
